### PR TITLE
Added TRASN and OVERDUMP generation for CDDA disks

### PR DESCRIPTION
**Pull request by AKuHAK**
- Added trash and overdump genereation for audio disks. Trash data comes
just after first data track. Overdump data - it is space between data
track and first audio track + first sectors of first audio track. So if
we concatenate CDROM.BIN and OVERDUMP.BIN we will get beginning of
CDMAGE generated bin file
- Implement more better cue sheet generation.

### CODE REVIEW

**Comment by Hykem** [comment]
AKuHAK, please correct what DeadlySystem mentioned. It's preferable to use "sizeof" instead of random values to keep a better track of code changes. Thanks!

**Comment by AKuHAK** [comment]
As about trash. I will try to explain it better:
As about generated ISO.BIN. It can be divided into 4 parts:
1part) First data track without fixed ECC errors
2part) Trash data (I don't know what is that - just random bytes? or something else?)
3part) Free space between data track and first audio track (filled with zeros)
4part) First sectors of first audio track (less than 16)
As we know ISO.BIN consist of pieces of 16 sectors (9300h bytes - just remark).
CDROM.BIN is generated from 1part. All ECC errors are fixed.
2part, 3part and 4part compressed sectors are marked with ISO_ENTRY->marker = 0

Next. About redump images. They consist of bin files. If there are audio tracks then first data track contains one unrecovered ECC error in last 60 bytes of track. it is because this is the only ECC error that is PHYSICALLY on the disc (or maybe im wrong? but I understand redump thread in such way). But anyway some cd drives recover these ECC error automatically. And in any case it is ERROR!!! Yeap it has historical meaning but it is still error in image which have to be recovered.

We can recover it in 2 ways: cdmage or pst001z. Anyway our new FIXED redump data.bin will be the same as CDROM.BIN. I don't know a way to undo this action - maybe it is impossible so redump hashes are useless for mixed discs.

Next.
If we concatenate CDROM.BIN + 3part + 4part we will get some image (ok call it DATA_OVERDUMP.BIN)
If we open in CDMAGE redump.cue, fix this last sector error, save image as IMAGE.BIN, then cut from image.bin part with size of DATA_OVERDUMP.BIN we will get the same file as DATA_OVERDUMP.BIN
Other words IMAGE.BIN = CDROM.BIN + 3part + 4part + some data

Ok I will try to fix cue sheet generation.

**Comment by AKuHAK** [comment]
Sorry guys I don't really see serious reason to fix my cue sheet generation. If you have better code implementation you can fix my code bu unfortunately i dont have free time.

**Comment by DeadlySystem** [comment]
@Hykem will you make the fixes? I could do it as well, I plan to review both of @AKuHAK s pull requests in-depth anyway (the Diff on Github is very bad...) but it's probably gonna take 1 or 2 weeks.

**Comment by Hykem** [comment]
I'm going to merge for now since it's not breaking anything, but I'm going to review the code and apply the fixes in the next commit (also have to port changes for Linux version).

**Pull request merged**
